[package]
name = "hyrebet"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "common"}
colored = "3.0.0"
ctrlc = "3.5.0"

[profile.dev]
lto=false
codegen-units = 2
opt-level = 3

[workspace]
members = ["api", "auth", "static-fs"]
